[workspace]
changelog_path = "./CHANGELOG.md"
changelog_update = true # enable changelog update
dependencies_update = false # update dependencies with `cargo update`
git_release_enable = true # enable GitHub releases
pr_branch_prefix = "release-plz-" # PR branch prefix
pr_labels = ["release"] # add the `release` label to the release Pull Request

[changelog]
protect_breaking_commits = true # always include commits with breaking changes in the changelog
