# https://release-plz.dev/docs/github/quickstart
name: Release

permissions:
  pull-requests: write
  contents: write

on:
  workflow_dispatch:
    # inputs:
    #   logLevel:
    #     description: 'Log level'
    #     required: true
    #     default: 'warning'
    #     type: choice
    #     options:
    #       - info
    #       - warning
    #       - debug
    #   print_tags:
    #     description: 'True to print to STDOUT'
    #     required: true
    #     type: boolean
    #   tags:
    #     description: 'Test scenario tags'
    #     required: true
    #     type: string
    #   environment:
    #     description: 'Environment to run tests against'
    #     type: environment
    #     required: true

jobs:
  # Release unpublished packages.
  release-plz-release:
    name: Release-plz release
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      # - name: Install Rust toolchain
      #   uses: dtolnay/rust-toolchain@stable
      # - name: Run release-plz
      #   uses: release-plz/action@v0.5
      #   with:
      #     command: release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  # Create a PR with the new versions and changelog, preparing the next release.
  release-plz-pr:
    name: Release-plz PR
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    concurrency:
      group: release-plz-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      # - name: Install Rust toolchain
      #   uses: dtolnay/rust-toolchain@stable
      # - name: Run release-plz
      #   uses: release-plz/action@v0.5
      #   with:
      #     command: release-pr
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

# jobs:
#   run-tests:
#     name: Build and run tests, check code quality
#     runs-on: ubuntu-24.04
#     steps:
#       - uses: actions/checkout@v4
#         with:
#           persist-credentials: false
#       - uses: actions/setup-python@v3
#       - name: install pre-commit
#         run: pip install "pre-commit~=4.2.0"
#       - name: build for tests
#         run: make build
#       - name: check code quality
#         run: make check
#       - name: run tests
#         run: make test
#       - name: build for release
#         run: make release
